import { Geist, Geist_Mono } from 'next/font/google';

import '@/app/globals.css';
import Provider from '../../Provider';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' suppressHydrationWarning={true}>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{/* Runtime env injection for client-side config override */}
				<script
					dangerouslySetInnerHTML={{
						__html: `window.__ENV=${JSON.stringify({
							NEXT_PUBLIC_GOOGLE_CLIENT_ID:
								process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID ?? '',
							NEXT_PUBLIC_BACKEND_URL:
								process.env.NEXT_PUBLIC_BACKEND_URL ?? '',
							NEXT_PUBLIC_WS_URL: process.env.NEXT_PUBLIC_WS_URL ?? '',
							NODE_ENV: process.env.NODE_ENV ?? '',
						})}`,
					}}
				/>
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
